name: data515

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - requests
  - beautifulsoup4
  - tqdm
  - pyarrow

  # notebooks
  - jupyterlab
  - ipykernel

  # dev tools (used in CI)
  - pylint
  - coverage

  # pip support
  - pip

  - pip:
      - streamlit
      - dash
      - dash-bootstrap-components
      - plotly
      - altair
      - kroger-api
      - python-dotenv
      - build