name: build_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v3

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: data515
          environment-file: environment.yml
          auto-update-conda: true
          auto-activate-base: false

      # Install browser + webdriver for Selenium / Dash tests
      - name: Install Chrome + driver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      # Add chromedriver to PATH (important for Selenium)
      - name: Add chromedriver to PATH
        run: |
          echo "/usr/lib/chromium-browser/" >> $GITHUB_PATH
          echo "/usr/lib/chromium/" >> $GITHUB_PATH

      - name: Install project
        run: |
          pip install -e .

      - name: Run tests
        run: |
          coverage run -m pytest
          coverage report
          coverage lcov

      - name: Lint with pylint
        run: |
          pylint api app

      - name: Report coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov